### PR TITLE
Fix horizontal scroll not aligned to the bottom in chromium in dark mode

### LINKED ISSUE #47: Bottom scroll bar interaction is misaligned
When I want to grab bottom scrollbar at the bottom of the page i can't. I can get 2px into the bar and i still can't grab it. But at the same time i can go 2 pixels above the bar and still grab it. Could you please extend the area all the way to the bottom? It's small bar so it's way easier to just slam the cursor to the bottom and then scroll

https://github.com/dimdenGD/OldTweetDeck/assets/11545014/42bde9c7-57cc-4943-beef-b85c761ff5a8

### PR DESCRIPTION
**Pull request by Michal-Szczepaniak**
Fixes #47

### CODE REVIEW

**Comment by dimdenGD** [comment]
Just removing the style definition doesn't seem to be like a good solution, since it was definitely added there for a reason

**Comment by Michal-Szczepaniak** [comment]
It's only causing issue and nothing more

**Comment by dimdenGD** [comment]
I don't think someone who was working on TweetDeck at Twitter added this code just to annoy users and nothing else, it could be fixing something for specific users while breaking it for others, need to find logic for when `.needs-scroll-bottom-offset.scroll-styled-h` is added

**Comment by Michal-Szczepaniak** [comment]
@dimdenGD can you like merge it and then wonder later if it causes any issue?

**Pull request closed without merging**
